/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bugtrackingsystem;

import net.proteanit.sql.DbUtils;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import javax.swing.UIManager;

/**
 *
 * @author m639a
 */
public final class Administrator extends javax.swing.JFrame {

    /**
     * Creates new form Administrator
     */
    public Administrator()
    {
        initComponents();
        admin.getConnected("SELECT * FROM ACTIVITIES ORDER BY DATE DESC, TIME DESC");
        omniTable.setModel(DbUtils.resultSetToTableModel(admin.getResObj()));
        this.setLocationRelativeTo(null);
        profileLabel.setText(CurrentUser.user);
    }
    
    //Controller
    AdminController admin = new AdminController();
    
    //Color global variables
    Color black = Color.decode("#323232");
    Color gray = Color.decode("#3B3B3B");
    Color green = Color.decode("#6DB193");
    Color purple = Color.decode("#9659A5");
    
    //Global variable to choose tabs
    int choice = 0;
    int table = 0;
    public int infoState = -1;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JPanel();
        profileLabel = new javax.swing.JLabel();
        usersLabel = new javax.swing.JLabel();
        activitiesLabel = new javax.swing.JLabel();
        projectsLabel = new javax.swing.JLabel();
        bugsLabel = new javax.swing.JLabel();
        logoutLabel = new javax.swing.JLabel();
        mainPanel = new javax.swing.JTabbedPane();
        activitiesPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        omniTable = new javax.swing.JTable();
        monitorLabel = new javax.swing.JLabel();
        failedLabel = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        usersPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        updateButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        userSearch = new javax.swing.JTextField();
        addUserButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        projectsPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        projectsTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        projectSearch = new javax.swing.JTextField();
        bugsPanel = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        bugsTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        bugSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(50, 50, 50));
        sidePanel.setPreferredSize(new java.awt.Dimension(340, 768));

        profileLabel.setBackground(new java.awt.Color(40, 40, 40));
        profileLabel.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        profileLabel.setForeground(new java.awt.Color(133, 89, 165));
        profileLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bugtrackingsystem/icons/images/person tester.png"))); // NOI18N
        profileLabel.setText("Admin");
        profileLabel.setOpaque(true);
        profileLabel.setPreferredSize(new java.awt.Dimension(350, 63));

        usersLabel.setBackground(new java.awt.Color(50, 50, 50));
        usersLabel.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        usersLabel.setForeground(new java.awt.Color(109, 177, 147));
        usersLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bugtrackingsystem/icons/images/users.png"))); // NOI18N
        usersLabel.setText(" Users");
        usersLabel.setOpaque(true);
        usersLabel.setPreferredSize(new java.awt.Dimension(280, 75));
        usersLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usersLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usersLabelMouseExited(evt);
            }
        });

        activitiesLabel.setBackground(new java.awt.Color(133, 89, 165));
        activitiesLabel.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        activitiesLabel.setForeground(new java.awt.Color(50, 50, 50));
        activitiesLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bugtrackingsystem/icons/images/dashboard.png"))); // NOI18N
        activitiesLabel.setText("Activities");
        activitiesLabel.setOpaque(true);
        activitiesLabel.setPreferredSize(new java.awt.Dimension(280, 75));
        activitiesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                activitiesLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                activitiesLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                activitiesLabelMouseExited(evt);
            }
        });

        projectsLabel.setBackground(new java.awt.Color(50, 50, 50));
        projectsLabel.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        projectsLabel.setForeground(new java.awt.Color(109, 177, 147));
        projectsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bugtrackingsystem/icons/images/projects.png"))); // NOI18N
        projectsLabel.setText("    Projects");
        projectsLabel.setOpaque(true);
        projectsLabel.setPreferredSize(new java.awt.Dimension(280, 75));
        projectsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                projectsLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                projectsLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                projectsLabelMouseExited(evt);
            }
        });

        bugsLabel.setBackground(new java.awt.Color(50, 50, 50));
        bugsLabel.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        bugsLabel.setForeground(new java.awt.Color(109, 177, 147));
        bugsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bugtrackingsystem/icons/images/bugs.png"))); // NOI18N
        bugsLabel.setText("   Bugs");
        bugsLabel.setOpaque(true);
        bugsLabel.setPreferredSize(new java.awt.Dimension(280, 75));
        bugsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bugsLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bugsLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bugsLabelMouseExited(evt);
            }
        });

        logoutLabel.setBackground(new java.awt.Color(50, 50, 50));
        logoutLabel.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        logoutLabel.setForeground(new java.awt.Color(109, 177, 147));
        logoutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bugtrackingsystem/icons/images/logout2.png"))); // NOI18N
        logoutLabel.setText("    Logout");
        logoutLabel.setOpaque(true);
        logoutLabel.setPreferredSize(new java.awt.Dimension(280, 75));
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(profileLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bugsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projectsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(usersLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(activitiesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addComponent(profileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(activitiesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(usersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(projectsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(bugsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(logoutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        getContentPane().add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 770));

        mainPanel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mainPanel.setInheritsPopupMenu(true);
        mainPanel.setPreferredSize(new java.awt.Dimension(1040, 800));

        activitiesPanel.setBackground(new java.awt.Color(217, 217, 217));

        omniTable.setAutoCreateRowSorter(true);
        omniTable.setBackground(new java.awt.Color(50, 50, 50));
        omniTable.setForeground(new java.awt.Color(217, 217, 217));
        omniTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        omniTable.setPreferredSize(new java.awt.Dimension(535, 1320));
        omniTable.setRowHeight(40);
        omniTable.setRowMargin(6);
        omniTable.setSelectionBackground(new java.awt.Color(109, 177, 147));
        omniTable.setSelectionForeground(new java.awt.Color(50, 50, 50));
        omniTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(omniTable);

        monitorLabel.setBackground(new java.awt.Color(133, 89, 165));
        monitorLabel.setFont(new java.awt.Font("Times New Roman", 0, 21)); // NOI18N
        monitorLabel.setForeground(new java.awt.Color(50, 50, 50));
        monitorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monitorLabel.setText("User Activities");
        monitorLabel.setToolTipText("Change table view to User Activities");
        monitorLabel.setOpaque(true);
        monitorLabel.setPreferredSize(new java.awt.Dimension(170, 35));
        monitorLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monitorLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                monitorLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                monitorLabelMouseExited(evt);
            }
        });

        failedLabel.setBackground(new java.awt.Color(50, 50, 50));
        failedLabel.setFont(new java.awt.Font("Times New Roman", 0, 21)); // NOI18N
        failedLabel.setForeground(new java.awt.Color(133, 89, 165));
        failedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        failedLabel.setText("Login Attempts");
        failedLabel.setToolTipText("Change table view to Login Attempts");
        failedLabel.setOpaque(true);
        failedLabel.setPreferredSize(new java.awt.Dimension(170, 35));
        failedLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                failedLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                failedLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                failedLabelMouseExited(evt);
            }
        });

        searchField.setBackground(new java.awt.Color(50, 50, 50));
        searchField.setFont(new java.awt.Font("Times New Roman", 0, 21)); // NOI18N
        searchField.setForeground(new java.awt.Color(217, 217, 217));
        searchField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        searchField.setToolTipText("Enter your search query");
        searchField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        searchField.setPreferredSize(new java.awt.Dimension(520, 35));
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
        });

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bugtrackingsystem/icons/images/search2.png"))); // NOI18N
        jLabel15.setPreferredSize(new java.awt.Dimension(75, 70));

        jPanel3.setBackground(new java.awt.Color(50, 50, 50));
        jPanel3.setPreferredSize(new java.awt.Dimension(1035, 75));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout activitiesPanelLayout = new javax.swing.GroupLayout(activitiesPanel);
        activitiesPanel.setLayout(activitiesPanelLayout);
        activitiesPanelLayout.setHorizontalGroup(
            activitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activitiesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(activitiesPanelLayout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(activitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(activitiesPanelLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(monitorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(failedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(activitiesPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(258, 258, 258))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        activitiesPanelLayout.setVerticalGroup(
            activitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, activitiesPanelLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(activitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(activitiesPanelLayout.createSequentialGroup()
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(activitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(monitorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(failedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        mainPanel.addTab("Activities", activitiesPanel);

        usersPanel.setBackground(new java.awt.Color(217, 217, 217));

        usersTable.setBackground(new java.awt.Color(50, 50, 50));
        usersTable.setForeground(new java.awt.Color(217, 217, 217));
        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        usersTable.setMinimumSize(new java.awt.Dimension(540, 1320));
        usersTable.setPreferredSize(new java.awt.Dimension(535, 1320));
        usersTable.setRowHeight(40);
        usersTable.setRowMargin(6);
        usersTable.setSelectionBackground(new java.awt.Color(109, 177, 147));
        usersTable.setSelectionForeground(new java.awt.Color(50, 50, 50));
        usersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(usersTable);

        jPanel4.setBackground(new java.awt.Color(50, 50, 50));

        updateButton.setBackground(new java.awt.Color(133, 89, 165));
        updateButton.setFont(new java.awt.Font("Times New Roman", 0, 21)); // NOI18N
        updateButton.setForeground(new java.awt.Color(50, 50, 50));
        updateButton.setText("Update");
        updateButton.setToolTipText("Updates table contents");
        updateButton.setPreferredSize(new java.awt.Dimension(90, 40));
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bugtrackingsystem/icons/images/search2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(75, 70));

        userSearch.setBackground(new java.awt.Color(50, 50, 50));
        userSearch.setForeground(new java.awt.Color(217, 217, 217));
        userSearch.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        userSearch.setToolTipText("Enter your search query");
        userSearch.setPreferredSize(new java.awt.Dimension(520, 35));
        userSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                userSearchKeyReleased(evt);
            }
        });

        addUserButton.setBackground(new java.awt.Color(109, 177, 147));
        addUserButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        addUserButton.setForeground(new java.awt.Color(50, 50, 50));
        addUserButton.setText("Add User");
        addUserButton.setPreferredSize(new java.awt.Dimension(250, 45));
        addUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserButtonActionPerformed(evt);
            }
        });

        DeleteButton.setBackground(new java.awt.Color(109, 177, 147));
        DeleteButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        DeleteButton.setForeground(new java.awt.Color(50, 50, 50));
        DeleteButton.setText("Delete All");
        DeleteButton.setToolTipText("Deletes all users");
        DeleteButton.setPreferredSize(new java.awt.Dimension(250, 45));

        javax.swing.GroupLayout usersPanelLayout = new javax.swing.GroupLayout(usersPanel);
        usersPanel.setLayout(usersPanelLayout);
        usersPanelLayout.setHorizontalGroup(
            usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1011, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(usersPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(258, 258, 258))
            .addGroup(usersPanelLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(addUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
        );
        usersPanelLayout.setVerticalGroup(
            usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usersPanelLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        mainPanel.addTab("Users", usersPanel);

        projectsPanel.setBackground(new java.awt.Color(217, 217, 217));

        projectsTable.setBackground(new java.awt.Color(50, 50, 50));
        projectsTable.setForeground(new java.awt.Color(217, 217, 217));
        projectsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        projectsTable.setPreferredSize(new java.awt.Dimension(535, 1320));
        projectsTable.setRowHeight(40);
        projectsTable.setRowMargin(6);
        projectsTable.setSelectionBackground(new java.awt.Color(109, 177, 147));
        projectsTable.setSelectionForeground(new java.awt.Color(50, 50, 50));
        jScrollPane4.setViewportView(projectsTable);

        jPanel2.setBackground(new java.awt.Color(50, 50, 50));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bugtrackingsystem/icons/images/search2.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setPreferredSize(new java.awt.Dimension(75, 70));

        projectSearch.setBackground(new java.awt.Color(50, 50, 50));
        projectSearch.setForeground(new java.awt.Color(217, 217, 217));
        projectSearch.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        projectSearch.setToolTipText("Enter your search query");
        projectSearch.setPreferredSize(new java.awt.Dimension(520, 35));
        projectSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                projectSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout projectsPanelLayout = new javax.swing.GroupLayout(projectsPanel);
        projectsPanel.setLayout(projectsPanelLayout);
        projectsPanelLayout.setHorizontalGroup(
            projectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, projectsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(projectsPanelLayout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(projectSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(258, 258, 258))
        );
        projectsPanelLayout.setVerticalGroup(
            projectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, projectsPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(projectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projectSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );

        mainPanel.addTab("Projects", projectsPanel);

        bugsPanel.setBackground(new java.awt.Color(217, 217, 217));

        bugsTable.setBackground(new java.awt.Color(50, 50, 50));
        bugsTable.setForeground(new java.awt.Color(217, 217, 217));
        bugsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        bugsTable.setPreferredSize(new java.awt.Dimension(535, 1320));
        bugsTable.setRowHeight(40);
        bugsTable.setRowMargin(6);
        bugsTable.setSelectionBackground(new java.awt.Color(109, 177, 147));
        bugsTable.setSelectionForeground(new java.awt.Color(50, 50, 50));
        jScrollPane5.setViewportView(bugsTable);

        jPanel1.setBackground(new java.awt.Color(50, 50, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bugtrackingsystem/icons/images/search2.png"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(75, 70));

        bugSearch.setBackground(new java.awt.Color(50, 50, 50));
        bugSearch.setForeground(new java.awt.Color(217, 217, 217));
        bugSearch.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        bugSearch.setToolTipText("Enter your search query");
        bugSearch.setPreferredSize(new java.awt.Dimension(520, 35));
        bugSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bugSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout bugsPanelLayout = new javax.swing.GroupLayout(bugsPanel);
        bugsPanel.setLayout(bugsPanelLayout);
        bugsPanelLayout.setHorizontalGroup(
            bugsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bugsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1011, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bugsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bugSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(258, 258, 258))
        );
        bugsPanelLayout.setVerticalGroup(
            bugsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bugsPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(bugsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bugsPanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bugsPanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(bugSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );

        mainPanel.addTab("Bugs", bugsPanel);

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, -50, 1040, 820));
        mainPanel.getAccessibleContext().setAccessibleDescription("Activites");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void activitiesLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_activitiesLabelMouseClicked
        choice = 0;
        activitiesLabel.setBackground(purple);
        activitiesLabel.setForeground(black);
        mainPanel.setSelectedIndex(choice);
        usersLabelMouseExited(evt);
        projectsLabelMouseExited(evt);
        bugsLabelMouseExited(evt);
    }//GEN-LAST:event_activitiesLabelMouseClicked

    private void activitiesLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_activitiesLabelMouseEntered
        if (choice == 0 || choice == -1){}
        else
            activitiesLabel.setBackground(gray);
            
    }//GEN-LAST:event_activitiesLabelMouseEntered

    private void activitiesLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_activitiesLabelMouseExited
        if (choice == 0 || choice == -1){}
        else
        {
            activitiesLabel.setBackground(black);
            activitiesLabel.setForeground(green);
        }
    }//GEN-LAST:event_activitiesLabelMouseExited

    private void usersLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersLabelMouseClicked
        choice = 1;
        usersLabel.setBackground(purple);
        usersLabel.setForeground(black);
        mainPanel.setSelectedIndex(choice);
        activitiesLabelMouseExited(evt);
        projectsLabelMouseExited(evt);
        bugsLabelMouseExited(evt);
        
        admin.viewUsers();
        usersTable.setModel(DbUtils.resultSetToTableModel(admin.getResObj()));
    }//GEN-LAST:event_usersLabelMouseClicked

    private void usersLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersLabelMouseEntered
        if (choice == 1){}
        else
            usersLabel.setBackground(gray);
    }//GEN-LAST:event_usersLabelMouseEntered

    private void usersLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersLabelMouseExited
        if (choice == 1){}
        else
        {
            usersLabel.setBackground(black);
            usersLabel.setForeground(green);
        }
    }//GEN-LAST:event_usersLabelMouseExited

    private void projectsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectsLabelMouseClicked
        choice = 2;
        projectsLabel.setBackground(purple);
        projectsLabel.setForeground(black);
        mainPanel.setSelectedIndex(choice);
        usersLabelMouseExited(evt);
        activitiesLabelMouseExited(evt);
        bugsLabelMouseExited(evt);
        
        admin.viewProjects();
        projectsTable.setModel(DbUtils.resultSetToTableModel(admin.getResObj()));
    }//GEN-LAST:event_projectsLabelMouseClicked

    private void projectsLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectsLabelMouseEntered
        if (choice == 2){}
        else
            projectsLabel.setBackground(gray);
    }//GEN-LAST:event_projectsLabelMouseEntered

    private void projectsLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectsLabelMouseExited
        if (choice == 2){}
        else
        {
            projectsLabel.setBackground(black);
            projectsLabel.setForeground(green);
        }
    }//GEN-LAST:event_projectsLabelMouseExited

    private void bugsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bugsLabelMouseClicked
        choice = 3;
        bugsLabel.setBackground(purple);
        bugsLabel.setForeground(black);
        mainPanel.setSelectedIndex(choice);
        usersLabelMouseExited(evt);
        projectsLabelMouseExited(evt);
        activitiesLabelMouseExited(evt);
        
        admin.viewBugs();
        bugsTable.setModel(DbUtils.resultSetToTableModel(admin.getResObj()));
    }//GEN-LAST:event_bugsLabelMouseClicked

    private void bugsLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bugsLabelMouseEntered
        if (choice == 3){}
        else
            bugsLabel.setBackground(gray);
    }//GEN-LAST:event_bugsLabelMouseEntered

    private void bugsLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bugsLabelMouseExited
        if (choice == 3){}
        else
        {
            bugsLabel.setBackground(black);
            bugsLabel.setForeground(green);
        }
    }//GEN-LAST:event_bugsLabelMouseExited

    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutLabelMouseClicked

    private void logoutLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseEntered
        logoutLabel.setBackground(gray);
    }//GEN-LAST:event_logoutLabelMouseEntered

    private void logoutLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseExited
        logoutLabel.setBackground(black);
        logoutLabel.setForeground(green);
    }//GEN-LAST:event_logoutLabelMouseExited

    private void monitorLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monitorLabelMouseClicked
        table = 0;
        monitorLabel.setBackground(purple);
        monitorLabel.setForeground(black);
        failedLabelMouseExited(evt);
        
        admin.viewActivity();
        omniTable.setModel(DbUtils.resultSetToTableModel(admin.getResObj()));
    }//GEN-LAST:event_monitorLabelMouseClicked

    private void monitorLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monitorLabelMouseEntered
        if (table == 0 || table == -1){}
        else
            monitorLabel.setBackground(gray);
    }//GEN-LAST:event_monitorLabelMouseEntered

    private void monitorLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monitorLabelMouseExited
        if (table == 0 || table == -1){}
        else
        {
            monitorLabel.setBackground(black);
            monitorLabel.setForeground(purple);
        }
    }//GEN-LAST:event_monitorLabelMouseExited

    private void failedLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_failedLabelMouseClicked
        table = 1;
        failedLabel.setBackground(purple);
        failedLabel.setForeground(black);
        monitorLabelMouseExited(evt);
        
        admin.viewAttempts();
        omniTable.setModel(DbUtils.resultSetToTableModel(admin.getResObj()));
    }//GEN-LAST:event_failedLabelMouseClicked

    private void failedLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_failedLabelMouseEntered
        if (table == 1){}
        else
            failedLabel.setBackground(gray);
    }//GEN-LAST:event_failedLabelMouseEntered

    private void failedLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_failedLabelMouseExited
        if (table == 1){}
        else
        {
            failedLabel.setBackground(black);
            failedLabel.setForeground(purple);
        }
    }//GEN-LAST:event_failedLabelMouseExited

    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        admin.searchOmni(table,searchField.getText());
        omniTable.setModel(DbUtils.resultSetToTableModel(admin.getResObj()));
    }//GEN-LAST:event_searchFieldKeyReleased

    private void userSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userSearchKeyReleased
        admin.searchUsers(userSearch.getText());
        usersTable.setModel(DbUtils.resultSetToTableModel(admin.getResObj()));
    }//GEN-LAST:event_userSearchKeyReleased

    private void projectSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_projectSearchKeyReleased
        admin.searchProjects(projectSearch.getText());
        projectsTable.setModel(DbUtils.resultSetToTableModel(admin.getResObj()));
    }//GEN-LAST:event_projectSearchKeyReleased

    private void bugSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bugSearchKeyReleased
        admin.searchBugs(bugSearch.getText());
        bugsTable.setModel(DbUtils.resultSetToTableModel(admin.getResObj()));
    }//GEN-LAST:event_bugSearchKeyReleased

    private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserButtonActionPerformed
        UserInfo add = new UserInfo(0);
        add.setVisible(true);
    }//GEN-LAST:event_addUserButtonActionPerformed

    private void usersTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersTableMouseClicked
        try
        {   
            int selectedID = (int) usersTable.getValueAt(usersTable.getSelectedRow(),0);
            UserInfo add = new UserInfo(selectedID);
            add.setVisible(true);
        }
        catch (Exception ex)
        {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_usersTableMouseClicked

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        admin.viewUsers();
        usersTable.setModel(DbUtils.resultSetToTableModel(admin.getResObj()));
    }//GEN-LAST:event_updateButtonActionPerformed

    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try 
        {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } 
        catch (Exception e)
        {
            e.printStackTrace();
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(() -> {
            new Administrator().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteButton;
    private javax.swing.JLabel activitiesLabel;
    private javax.swing.JPanel activitiesPanel;
    private javax.swing.JButton addUserButton;
    private javax.swing.JTextField bugSearch;
    private javax.swing.JLabel bugsLabel;
    private javax.swing.JPanel bugsPanel;
    private javax.swing.JTable bugsTable;
    private javax.swing.JLabel failedLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JTabbedPane mainPanel;
    private javax.swing.JLabel monitorLabel;
    private javax.swing.JTable omniTable;
    private javax.swing.JLabel profileLabel;
    private javax.swing.JTextField projectSearch;
    private javax.swing.JLabel projectsLabel;
    private javax.swing.JPanel projectsPanel;
    private javax.swing.JTable projectsTable;
    private javax.swing.JTextField searchField;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JButton updateButton;
    private javax.swing.JTextField userSearch;
    private javax.swing.JLabel usersLabel;
    private javax.swing.JPanel usersPanel;
    private javax.swing.JTable usersTable;
    // End of variables declaration//GEN-END:variables
}
