/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bugtrackingsystem;

import com.formdev.flatlaf.FlatDarkLaf;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author mariam
 */
public class BugInformation extends javax.swing.JFrame implements Colors {

    /**
     * Creates new form BugInformation
     * @param choice
     */
    
    //CONTROLLER
    TesterController info = new TesterController();
    
    public BugInformation(int choice) {
        initComponents();
        
        //SET THE JFRAME TO BE IN THE CENTER 
        this.setLocationRelativeTo(null);
        
        //GETCONNECTED
        confirmButton.setEnabled(false);
        String[] arr = info.selectBug(choice);
        idField.setText(arr[0]);
        nameField.setText(arr[1]);
        severityField.setText(arr[2]);
        TypeField.setText(arr[3]);
        StatusBox.setSelectedIndex(0);
        DescriptionField.setText(arr[4]);

        idField.setEnabled(false);
        nameField.setEnabled(false);
        severityField.setEnabled(false);
        TypeField.setEnabled(false);
        StatusBox.setEnabled(false);
        DescriptionField.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BugInfojPanel = new javax.swing.JPanel();
        confirmButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        BugInfoLabel = new javax.swing.JLabel();
        ProjectIddLabel = new javax.swing.JLabel();
        BugNameLabel = new javax.swing.JLabel();
        SeverityLabel = new javax.swing.JLabel();
        TypeLabel = new javax.swing.JLabel();
        StatusLabel = new javax.swing.JLabel();
        DescriptionLabel = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        severityField = new javax.swing.JTextField();
        TypeField = new javax.swing.JTextField();
        StatusBox = new javax.swing.JComboBox<>();
        editButton = new javax.swing.JButton();
        DescriptionField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 700));
        setResizable(false);

        BugInfojPanel.setBackground(new java.awt.Color(50, 50, 50));
        BugInfojPanel.setForeground(new java.awt.Color(217, 217, 217));
        BugInfojPanel.setToolTipText("");
        BugInfojPanel.setPreferredSize(new java.awt.Dimension(800, 700));

        confirmButton.setBackground(new java.awt.Color(133, 89, 165));
        confirmButton.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(50, 50, 50));
        confirmButton.setText("Confirm");
        confirmButton.setPreferredSize(new java.awt.Dimension(150, 45));
        confirmButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                confirmButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                confirmButtonMouseExited(evt);
            }
        });
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        CancelButton.setBackground(new java.awt.Color(133, 89, 165));
        CancelButton.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        CancelButton.setForeground(new java.awt.Color(50, 50, 50));
        CancelButton.setText("Cancel");
        CancelButton.setPreferredSize(new java.awt.Dimension(150, 45));
        CancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CancelButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CancelButtonMouseExited(evt);
            }
        });
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        BugInfoLabel.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        BugInfoLabel.setForeground(new java.awt.Color(133, 89, 165));
        BugInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BugInfoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bugtrackingsystem/icons/images/bug-information-small.png"))); // NOI18N
        BugInfoLabel.setText("  Bug Information");
        BugInfoLabel.setPreferredSize(new java.awt.Dimension(800, 90));

        ProjectIddLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ProjectIddLabel.setForeground(new java.awt.Color(109, 177, 147));
        ProjectIddLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProjectIddLabel.setText("ProjectID");
        ProjectIddLabel.setPreferredSize(new java.awt.Dimension(150, 45));

        BugNameLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        BugNameLabel.setForeground(new java.awt.Color(109, 177, 147));
        BugNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BugNameLabel.setText("Name");
        BugNameLabel.setToolTipText("");
        BugNameLabel.setPreferredSize(new java.awt.Dimension(150, 45));

        SeverityLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        SeverityLabel.setForeground(new java.awt.Color(109, 177, 147));
        SeverityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SeverityLabel.setText("Severity");
        SeverityLabel.setToolTipText("");
        SeverityLabel.setPreferredSize(new java.awt.Dimension(150, 45));

        TypeLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        TypeLabel.setForeground(new java.awt.Color(109, 177, 147));
        TypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TypeLabel.setText("Type");
        TypeLabel.setPreferredSize(new java.awt.Dimension(150, 45));

        StatusLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        StatusLabel.setForeground(new java.awt.Color(109, 177, 147));
        StatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StatusLabel.setText("Status");
        StatusLabel.setPreferredSize(new java.awt.Dimension(150, 45));

        DescriptionLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        DescriptionLabel.setForeground(new java.awt.Color(109, 177, 147));
        DescriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DescriptionLabel.setText("Description");
        DescriptionLabel.setPreferredSize(new java.awt.Dimension(150, 95));

        idField.setBackground(new java.awt.Color(50, 50, 50));
        idField.setForeground(new java.awt.Color(217, 217, 217));
        idField.setPreferredSize(new java.awt.Dimension(200, 45));

        nameField.setBackground(new java.awt.Color(50, 50, 50));
        nameField.setForeground(new java.awt.Color(217, 217, 217));
        nameField.setPreferredSize(new java.awt.Dimension(200, 45));
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        severityField.setBackground(new java.awt.Color(50, 50, 50));
        severityField.setForeground(new java.awt.Color(217, 217, 217));
        severityField.setPreferredSize(new java.awt.Dimension(200, 45));

        TypeField.setBackground(new java.awt.Color(50, 50, 50));
        TypeField.setForeground(new java.awt.Color(217, 217, 217));
        TypeField.setPreferredSize(new java.awt.Dimension(200, 45));

        StatusBox.setBackground(new java.awt.Color(50, 50, 50));
        StatusBox.setForeground(new java.awt.Color(217, 217, 217));
        StatusBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "To be tested", "Closed" }));
        StatusBox.setMinimumSize(new java.awt.Dimension(77, 45));
        StatusBox.setPreferredSize(new java.awt.Dimension(77, 45));

        editButton.setBackground(new java.awt.Color(109, 177, 147));
        editButton.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        editButton.setForeground(new java.awt.Color(50, 50, 50));
        editButton.setText("Edit");
        editButton.setPreferredSize(new java.awt.Dimension(120, 45));
        editButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editButtonMouseExited(evt);
            }
        });
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        DescriptionField.setBackground(new java.awt.Color(50, 50, 50));
        DescriptionField.setForeground(new java.awt.Color(217, 217, 217));
        DescriptionField.setPreferredSize(new java.awt.Dimension(540, 95));

        javax.swing.GroupLayout BugInfojPanelLayout = new javax.swing.GroupLayout(BugInfojPanel);
        BugInfojPanel.setLayout(BugInfojPanelLayout);
        BugInfojPanelLayout.setHorizontalGroup(
            BugInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BugInfojPanelLayout.createSequentialGroup()
                .addComponent(BugInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(BugInfojPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BugInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BugNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProjectIddLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeverityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TypeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(BugInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(severityField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StatusBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TypeField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BugInfojPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DescriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(BugInfojPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        BugInfojPanelLayout.setVerticalGroup(
            BugInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BugInfojPanelLayout.createSequentialGroup()
                .addComponent(BugInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BugInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProjectIddLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(BugInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BugNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(BugInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SeverityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(severityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(BugInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(BugInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StatusBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(BugInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DescriptionField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DescriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(BugInfojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BugInfojPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BugInfojPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        int result ;

        result = info.editBug(StatusBox.getSelectedIndex());
        if (result == 1) {
            this.dispose();
            JOptionPane.showMessageDialog(null, "Information updated successfully, Please update the table!");
        }
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        StatusBox.setEnabled(true);
        confirmButton.setEnabled(true);
        editButton.setEnabled(false);
    }//GEN-LAST:event_editButtonActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void editButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseEntered
        editButton.setBackground(Purple);
    }//GEN-LAST:event_editButtonMouseEntered

    private void editButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseExited
        editButton.setBackground(Green);
    }//GEN-LAST:event_editButtonMouseExited

    private void confirmButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmButtonMouseEntered
        confirmButton.setBackground(Green);
    }//GEN-LAST:event_confirmButtonMouseEntered

    private void confirmButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmButtonMouseExited
        confirmButton.setBackground(Purple);
    }//GEN-LAST:event_confirmButtonMouseExited

    private void CancelButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelButtonMouseEntered
        CancelButton.setBackground(Green);
    }//GEN-LAST:event_CancelButtonMouseEntered

    private void CancelButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelButtonMouseExited
        CancelButton.setBackground(Purple);
    }//GEN-LAST:event_CancelButtonMouseExited

    private void CancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelButtonMouseClicked
        this.dispose();
    }//GEN-LAST:event_CancelButtonMouseClicked

    private void editButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_editButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try 
        {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } 
        catch (UnsupportedLookAndFeelException ex)
        {
            System.out.println(ex.getMessage());
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BugInfoLabel;
    private javax.swing.JPanel BugInfojPanel;
    private javax.swing.JLabel BugNameLabel;
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField DescriptionField;
    private javax.swing.JLabel DescriptionLabel;
    private javax.swing.JLabel ProjectIddLabel;
    private javax.swing.JLabel SeverityLabel;
    private javax.swing.JComboBox<String> StatusBox;
    private javax.swing.JLabel StatusLabel;
    private javax.swing.JTextField TypeField;
    private javax.swing.JLabel TypeLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField idField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField severityField;
    // End of variables declaration//GEN-END:variables
}
