/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bugtrackingsystem;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.*;
import net.proteanit.sql.DbUtils;
import static bugtrackingsystem.dataConnection.host;
import static bugtrackingsystem.dataConnection.pass;
import static bugtrackingsystem.dataConnection.uname;
import com.formdev.flatlaf.FlatDarkLaf;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author mariam
 */

  //DB connection objects
   
public class Devoloper extends javax.swing.JFrame implements Colors {

    public Devoloper() {
        this.counter = 0;
        initComponents();
        getConnected();
        this.setLocationRelativeTo(null);

       DeveloperName.setText(CurrentUser.user);
        
       proj_number.setText(String.valueOf(Card(0)));
       BUG_number.setText(String.valueOf(Card(1)));

    }
    Connection conObj = null;
    Statement smtObj = null;
    ResultSet resObj = null;
    
     PreparedStatement command;
     
    
    
    public void getConnected()
    {
        try
        {
            conObj = DriverManager.getConnection(host, uname, pass);
            smtObj = conObj.createStatement( ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY );
            command=conObj.prepareStatement("select PROJECTS.PROJECTNAME, PROJECTS.CREATIONDATE, BUGS.BUGNAME, BUGS.DATEASSIGNED FROM ASSIGNMENTS INNER JOIN PROJECTS ON PROJECTS.PROJECTID = ASSIGNMENTS.PROJECTID INNER JOIN BUGS ON BUGS.PROJECTID = ASSIGNMENTS.PROJECTID WHERE ASSIGNMENTS.USERID=? " );
            command.setInt(1,CurrentUser.id);
            resObj=command.executeQuery();
//resObj = smtObj.executeQuery("SELECT USERS.USERNAME, PROJECTS.PROJECTNAME, PROJECTS.CREATIONDATE FROM ASSIGNMENTS INNER JOIN PROJECTS ON PROJECTS.PROJECTID = ASSIGNMENTS.PROJECTID RIGHT JOIN USERS ON USERS.USERID = ASSIGNMENTS.USERID where projects.projectid=?");
            //resObj = smtObj.executeQuery("SELECT DISTINCT USERS.USERNAME, PROJECTS.PROJECTNAME FROM  ASSIGNMENTS INNER JOIN PROJECTS ON PROJECTS.PROJECTID = ASSIGNMENTS.PROJECTID INNER JOIN USERS ON USERS.USERID = ASSIGNMENTS.USERID INNER JOIN BUGS ON BUGS.PROJECTID=ASSIGNMENTS.PROJECTID");
           // resObj = smtObj.executeQuery("SELECT PROJECTS.PROJECTNAME FROM ASSIGNMENTS INNER JOIN PROJECTS ON PROJECTS.PROJECTID = ASSIGNMENTS.PROJECTID WHERE ASSIGNMENTS.USERID=? ");
            
            Dashboard_table.setModel(DbUtils.resultSetToTableModel(resObj));
        }
        catch (SQLException ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SidePanel = new javax.swing.JPanel();
        DeveloperName = new javax.swing.JLabel();
        testerLogo = new javax.swing.JLabel();
        Dashlogo = new javax.swing.JLabel();
        ProjectLogo = new javax.swing.JLabel();
        BugLogo = new javax.swing.JLabel();
        LogoutLogo = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Dashboard_table = new javax.swing.JTable();
        noOfProjects = new javax.swing.JPanel();
        proj_number = new javax.swing.JLabel();
        ProjectNumber = new javax.swing.JLabel();
        noOfBugs1 = new javax.swing.JPanel();
        BUG_number = new javax.swing.JLabel();
        BugNumber1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Projects_table = new javax.swing.JTable();
        LogoOfSearch = new javax.swing.JLabel();
        Search2 = new app.bolivia.swing.JCTextField();
        noOfProjects1 = new javax.swing.JPanel();
        proj_number_all = new javax.swing.JLabel();
        ProjectNumber2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Bugs_table = new javax.swing.JTable();
        LogoOfSearch1 = new javax.swing.JLabel();
        Search3 = new app.bolivia.swing.JCTextField();
        noOfBugs = new javax.swing.JPanel();
        BUG_number_all = new javax.swing.JLabel();
        BugNumber = new javax.swing.JLabel();
        BugDetails = new javax.swing.JPanel();
        CancelButton1 = new javax.swing.JButton();
        ConfirmButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        BugDetailsLabel = new javax.swing.JLabel();
        ProjectIdLabel = new javax.swing.JLabel();
        IDOfProject = new javax.swing.JTextField();
        NameLabel = new javax.swing.JLabel();
        NameOfBug = new javax.swing.JTextField();
        TesterIdLabel = new javax.swing.JLabel();
        IDOfTester = new javax.swing.JTextField();
        DeveloperNameLabel = new javax.swing.JLabel();
        IdOfDeveloper = new javax.swing.JTextField();
        DescriptionLabel = new javax.swing.JLabel();
        Description = new javax.swing.JTextField();
        StatusLabel = new javax.swing.JLabel();
        StatusBox = new javax.swing.JComboBox<>();
        SeverityLabel = new javax.swing.JLabel();
        SeverityBox = new javax.swing.JComboBox<>();
        TypeLabel = new javax.swing.JLabel();
        TypeBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(217, 217, 217));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SidePanel.setBackground(new java.awt.Color(50, 50, 50));
        SidePanel.setPreferredSize(new java.awt.Dimension(340, 768));

        DeveloperName.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        DeveloperName.setForeground(new java.awt.Color(133, 89, 165));
        DeveloperName.setText("Devoloper Name");

        testerLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bugtrackingsystem/icons/images/person tester.png"))); // NOI18N

        Dashlogo.setBackground(new java.awt.Color(133, 89, 165));
        Dashlogo.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        Dashlogo.setForeground(new java.awt.Color(50, 50, 50));
        Dashlogo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Dashlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bugtrackingsystem/icons/images/dashboard.png"))); // NOI18N
        Dashlogo.setText("     Dashboard");
        Dashlogo.setOpaque(true);
        Dashlogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashlogoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DashlogoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DashlogoMouseExited(evt);
            }
        });

        ProjectLogo.setBackground(new java.awt.Color(50, 50, 50));
        ProjectLogo.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        ProjectLogo.setForeground(new java.awt.Color(109, 177, 147));
        ProjectLogo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ProjectLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bugtrackingsystem/icons/images/projects.png"))); // NOI18N
        ProjectLogo.setText("        Projects");
        ProjectLogo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        ProjectLogo.setOpaque(true);
        ProjectLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProjectLogoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProjectLogoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProjectLogoMouseExited(evt);
            }
        });

        BugLogo.setBackground(new java.awt.Color(50, 50, 50));
        BugLogo.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        BugLogo.setForeground(new java.awt.Color(109, 177, 147));
        BugLogo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BugLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bugtrackingsystem/icons/images/bugs.png"))); // NOI18N
        BugLogo.setText("       Bugs");
        BugLogo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        BugLogo.setOpaque(true);
        BugLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BugLogoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BugLogoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BugLogoMouseExited(evt);
            }
        });

        LogoutLogo.setBackground(new java.awt.Color(50, 50, 50));
        LogoutLogo.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        LogoutLogo.setForeground(new java.awt.Color(109, 177, 147));
        LogoutLogo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LogoutLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bugtrackingsystem/icons/images/logout.png"))); // NOI18N
        LogoutLogo.setText("         logout");
        LogoutLogo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        LogoutLogo.setOpaque(true);
        LogoutLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutLogoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutLogoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutLogoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout SidePanelLayout = new javax.swing.GroupLayout(SidePanel);
        SidePanel.setLayout(SidePanelLayout);
        SidePanelLayout.setHorizontalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(testerLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22)
                .addComponent(DeveloperName, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addGroup(SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Dashlogo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProjectLogo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BugLogo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LogoutLogo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );
        SidePanelLayout.setVerticalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(testerLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DeveloperName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addComponent(Dashlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(ProjectLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(BugLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(LogoutLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        getContentPane().add(SidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 770));

        jPanel8.setBackground(new java.awt.Color(50, 50, 50));
        jPanel8.setPreferredSize(new java.awt.Dimension(1026, 60));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1026, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, -1, -1));

        jTabbedPane1.setBackground(new java.awt.Color(217, 217, 217));

        jPanel2.setBackground(new java.awt.Color(217, 217, 217));

        Dashboard_table.setBackground(new java.awt.Color(50, 50, 50));
        Dashboard_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Dashboard_table.setPreferredSize(new java.awt.Dimension(535, 1320));
        Dashboard_table.setRowHeight(35);
        jScrollPane1.setViewportView(Dashboard_table);

        noOfProjects.setBackground(new java.awt.Color(50, 50, 50));
        noOfProjects.setBorder(javax.swing.BorderFactory.createMatteBorder(20, 0, 0, 0, new java.awt.Color(133, 89, 165)));
        noOfProjects.setPreferredSize(new java.awt.Dimension(260, 140));

        proj_number.setBackground(new java.awt.Color(50, 50, 50));
        proj_number.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        proj_number.setForeground(new java.awt.Color(217, 217, 217));
        proj_number.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bugtrackingsystem/icons/images/projects.png"))); // NOI18N
        proj_number.setText(" 10");
        proj_number.setOpaque(true);

        javax.swing.GroupLayout noOfProjectsLayout = new javax.swing.GroupLayout(noOfProjects);
        noOfProjects.setLayout(noOfProjectsLayout);
        noOfProjectsLayout.setHorizontalGroup(
            noOfProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noOfProjectsLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(proj_number, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        noOfProjectsLayout.setVerticalGroup(
            noOfProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noOfProjectsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(proj_number)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        ProjectNumber.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ProjectNumber.setForeground(new java.awt.Color(50, 50, 50));
        ProjectNumber.setText("Number of projects assigned to you");

        noOfBugs1.setBackground(new java.awt.Color(50, 50, 50));
        noOfBugs1.setBorder(javax.swing.BorderFactory.createMatteBorder(20, 0, 0, 0, new java.awt.Color(109, 177, 147)));
        noOfBugs1.setPreferredSize(new java.awt.Dimension(260, 140));
        noOfBugs1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noOfBugs1MouseClicked(evt);
            }
        });

        BUG_number.setBackground(new java.awt.Color(50, 50, 50));
        BUG_number.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        BUG_number.setForeground(new java.awt.Color(217, 217, 217));
        BUG_number.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bugtrackingsystem/icons/images/bugs.png"))); // NOI18N
        BUG_number.setText("10");
        BUG_number.setOpaque(true);
        BUG_number.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BUG_numberMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout noOfBugs1Layout = new javax.swing.GroupLayout(noOfBugs1);
        noOfBugs1.setLayout(noOfBugs1Layout);
        noOfBugs1Layout.setHorizontalGroup(
            noOfBugs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noOfBugs1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(BUG_number, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        noOfBugs1Layout.setVerticalGroup(
            noOfBugs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noOfBugs1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(BUG_number)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        BugNumber1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BugNumber1.setForeground(new java.awt.Color(50, 50, 50));
        BugNumber1.setText("Number of bugs assigned to you:-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noOfProjects, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProjectNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(noOfBugs1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(BugNumber1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addGap(57, 57, 57))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProjectNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BugNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(noOfProjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noOfBugs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jPanel2);

        jPanel3.setBackground(new java.awt.Color(217, 217, 217));

        Projects_table.setBackground(new java.awt.Color(50, 50, 50));
        Projects_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Projects_table.setRowHeight(35);
        jScrollPane2.setViewportView(Projects_table);

        LogoOfSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bugtrackingsystem/icons/images/search2.png"))); // NOI18N
        LogoOfSearch.setText("jLabel1");

        Search2.setBackground(new java.awt.Color(217, 217, 217));
        Search2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(150, 89, 165)));
        Search2.setForeground(new java.awt.Color(109, 177, 147));
        Search2.setToolTipText("Make your search from here");
        Search2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Search2.setPhColor(new java.awt.Color(150, 89, 165));
        Search2.setPlaceholder("Search....");
        Search2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search2ActionPerformed(evt);
            }
        });
        Search2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Search2KeyReleased(evt);
            }
        });

        noOfProjects1.setBackground(new java.awt.Color(50, 50, 50));
        noOfProjects1.setBorder(javax.swing.BorderFactory.createMatteBorder(20, 0, 0, 0, new java.awt.Color(133, 89, 165)));
        noOfProjects1.setPreferredSize(new java.awt.Dimension(260, 140));

        proj_number_all.setBackground(new java.awt.Color(50, 50, 50));
        proj_number_all.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        proj_number_all.setForeground(new java.awt.Color(217, 217, 217));
        proj_number_all.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bugtrackingsystem/icons/images/projects.png"))); // NOI18N
        proj_number_all.setText(" 10");
        proj_number_all.setOpaque(true);

        javax.swing.GroupLayout noOfProjects1Layout = new javax.swing.GroupLayout(noOfProjects1);
        noOfProjects1.setLayout(noOfProjects1Layout);
        noOfProjects1Layout.setHorizontalGroup(
            noOfProjects1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noOfProjects1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(proj_number_all, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        noOfProjects1Layout.setVerticalGroup(
            noOfProjects1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noOfProjects1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(proj_number_all)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        ProjectNumber2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ProjectNumber2.setForeground(new java.awt.Color(50, 50, 50));
        ProjectNumber2.setText("Number of projects assigned to you");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1025, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(noOfProjects1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LogoOfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Search2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(ProjectNumber2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(ProjectNumber2)
                        .addGap(14, 14, 14)
                        .addComponent(noOfProjects1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Search2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogoOfSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("tab2", jPanel3);

        jPanel4.setBackground(new java.awt.Color(217, 217, 217));

        Bugs_table.setBackground(new java.awt.Color(50, 50, 50));
        Bugs_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Bugs_table.setRowHeight(35);
        Bugs_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bugs_tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Bugs_table);

        LogoOfSearch1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bugtrackingsystem/icons/images/search2.png"))); // NOI18N
        LogoOfSearch1.setText("jLabel1");

        Search3.setBackground(new java.awt.Color(217, 217, 217));
        Search3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(150, 89, 165)));
        Search3.setForeground(new java.awt.Color(109, 177, 147));
        Search3.setToolTipText("Make your search from here");
        Search3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Search3.setPhColor(new java.awt.Color(150, 89, 165));
        Search3.setPlaceholder("Search....");
        Search3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Search3KeyReleased(evt);
            }
        });

        noOfBugs.setBackground(new java.awt.Color(50, 50, 50));
        noOfBugs.setBorder(javax.swing.BorderFactory.createMatteBorder(20, 0, 0, 0, new java.awt.Color(109, 177, 147)));
        noOfBugs.setPreferredSize(new java.awt.Dimension(260, 140));
        noOfBugs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noOfBugsMouseClicked(evt);
            }
        });

        BUG_number_all.setBackground(new java.awt.Color(50, 50, 50));
        BUG_number_all.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        BUG_number_all.setForeground(new java.awt.Color(217, 217, 217));
        BUG_number_all.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bugtrackingsystem/icons/images/bugs.png"))); // NOI18N
        BUG_number_all.setText("10");
        BUG_number_all.setOpaque(true);
        BUG_number_all.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BUG_number_allMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout noOfBugsLayout = new javax.swing.GroupLayout(noOfBugs);
        noOfBugs.setLayout(noOfBugsLayout);
        noOfBugsLayout.setHorizontalGroup(
            noOfBugsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noOfBugsLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(BUG_number_all, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        noOfBugsLayout.setVerticalGroup(
            noOfBugsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noOfBugsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(BUG_number_all)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        BugNumber.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BugNumber.setForeground(new java.awt.Color(50, 50, 50));
        BugNumber.setText("Number of bugs assigned to you:-");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(noOfBugs, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addComponent(LogoOfSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Search3, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(BugNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LogoOfSearch1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Search3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BugNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noOfBugs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("tab3", jPanel4);

        BugDetails.setBackground(new java.awt.Color(50, 50, 50));
        BugDetails.setForeground(new java.awt.Color(217, 217, 217));
        BugDetails.setToolTipText("");
        BugDetails.setMaximumSize(new java.awt.Dimension(3700, 3700));
        BugDetails.setPreferredSize(new java.awt.Dimension(1025, 733));

        CancelButton1.setBackground(new java.awt.Color(133, 89, 165));
        CancelButton1.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        CancelButton1.setForeground(new java.awt.Color(50, 50, 50));
        CancelButton1.setText("Cancel");
        CancelButton1.setPreferredSize(new java.awt.Dimension(150, 45));
        CancelButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CancelButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CancelButton1MouseExited(evt);
            }
        });
        CancelButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButton1ActionPerformed(evt);
            }
        });

        ConfirmButton.setBackground(new java.awt.Color(133, 89, 165));
        ConfirmButton.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        ConfirmButton.setForeground(new java.awt.Color(50, 50, 50));
        ConfirmButton.setText("Confirm");
        ConfirmButton.setPreferredSize(new java.awt.Dimension(150, 45));
        ConfirmButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConfirmButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ConfirmButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ConfirmButtonMouseExited(evt);
            }
        });
        ConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmButtonActionPerformed(evt);
            }
        });

        EditButton.setBackground(new java.awt.Color(109, 177, 147));
        EditButton.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        EditButton.setForeground(new java.awt.Color(50, 50, 50));
        EditButton.setText("Edit");
        EditButton.setPreferredSize(new java.awt.Dimension(150, 45));
        EditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditButtonMouseExited(evt);
            }
        });
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });

        BugDetailsLabel.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        BugDetailsLabel.setForeground(new java.awt.Color(133, 89, 165));
        BugDetailsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BugDetailsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bugtrackingsystem/icons/images/bugs.png"))); // NOI18N
        BugDetailsLabel.setText("Bug Details:");
        BugDetailsLabel.setPreferredSize(new java.awt.Dimension(800, 90));

        ProjectIdLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ProjectIdLabel.setForeground(new java.awt.Color(109, 177, 147));
        ProjectIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProjectIdLabel.setText("Project ID:");
        ProjectIdLabel.setPreferredSize(new java.awt.Dimension(150, 45));

        IDOfProject.setBackground(new java.awt.Color(50, 50, 50));
        IDOfProject.setForeground(new java.awt.Color(217, 217, 217));
        IDOfProject.setPreferredSize(new java.awt.Dimension(219, 45));

        NameLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(109, 177, 147));
        NameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameLabel.setText("Bug Name:");
        NameLabel.setToolTipText("");
        NameLabel.setPreferredSize(new java.awt.Dimension(150, 45));

        NameOfBug.setBackground(new java.awt.Color(50, 50, 50));
        NameOfBug.setForeground(new java.awt.Color(217, 217, 217));
        NameOfBug.setPreferredSize(new java.awt.Dimension(219, 45));
        NameOfBug.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                NameOfBugFocusLost(evt);
            }
        });

        TesterIdLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        TesterIdLabel.setForeground(new java.awt.Color(109, 177, 147));
        TesterIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TesterIdLabel.setText("Reporter Name:");
        TesterIdLabel.setPreferredSize(new java.awt.Dimension(150, 45));

        IDOfTester.setBackground(new java.awt.Color(50, 50, 50));
        IDOfTester.setForeground(new java.awt.Color(217, 217, 217));
        IDOfTester.setPreferredSize(new java.awt.Dimension(219, 45));

        DeveloperNameLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        DeveloperNameLabel.setForeground(new java.awt.Color(109, 177, 147));
        DeveloperNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DeveloperNameLabel.setText("Developer Name:");
        DeveloperNameLabel.setPreferredSize(new java.awt.Dimension(150, 45));

        IdOfDeveloper.setBackground(new java.awt.Color(50, 50, 50));
        IdOfDeveloper.setForeground(new java.awt.Color(217, 217, 217));
        IdOfDeveloper.setPreferredSize(new java.awt.Dimension(219, 45));
        IdOfDeveloper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdOfDeveloperActionPerformed(evt);
            }
        });

        DescriptionLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        DescriptionLabel.setForeground(new java.awt.Color(109, 177, 147));
        DescriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DescriptionLabel.setText("Description:");
        DescriptionLabel.setPreferredSize(new java.awt.Dimension(150, 45));

        Description.setBackground(new java.awt.Color(50, 50, 50));
        Description.setForeground(new java.awt.Color(217, 217, 217));
        Description.setPreferredSize(new java.awt.Dimension(743, 89));
        Description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescriptionActionPerformed(evt);
            }
        });

        StatusLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        StatusLabel.setForeground(new java.awt.Color(109, 177, 147));
        StatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StatusLabel.setText("Status:");
        StatusLabel.setPreferredSize(new java.awt.Dimension(150, 45));

        StatusBox.setBackground(new java.awt.Color(50, 50, 50));
        StatusBox.setForeground(new java.awt.Color(217, 217, 217));
        StatusBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "Open", "In progress", "To be tested", "Closed" }));

        SeverityLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        SeverityLabel.setForeground(new java.awt.Color(109, 177, 147));
        SeverityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SeverityLabel.setText("Severity:");
        SeverityLabel.setPreferredSize(new java.awt.Dimension(150, 45));

        SeverityBox.setBackground(new java.awt.Color(50, 50, 50));
        SeverityBox.setForeground(new java.awt.Color(217, 217, 217));
        SeverityBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "Critical", "Major", "Moderate", "Minor", "Cosmitic" }));

        TypeLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        TypeLabel.setForeground(new java.awt.Color(109, 177, 147));
        TypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TypeLabel.setText("Type:");
        TypeLabel.setPreferredSize(new java.awt.Dimension(150, 45));

        TypeBox.setBackground(new java.awt.Color(50, 50, 50));
        TypeBox.setForeground(new java.awt.Color(217, 217, 217));
        TypeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "Content", "Functional", "Visual", " " }));

        javax.swing.GroupLayout BugDetailsLayout = new javax.swing.GroupLayout(BugDetails);
        BugDetails.setLayout(BugDetailsLayout);
        BugDetailsLayout.setHorizontalGroup(
            BugDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BugDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BugDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BugDetailsLayout.createSequentialGroup()
                        .addComponent(BugDetailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(BugDetailsLayout.createSequentialGroup()
                        .addGroup(BugDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(DescriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(DeveloperNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TesterIdLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ProjectIdLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BugDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BugDetailsLayout.createSequentialGroup()
                                .addComponent(ConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CancelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BugDetailsLayout.createSequentialGroup()
                                .addGroup(BugDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BugDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(NameOfBug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(IDOfProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(IDOfTester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IdOfDeveloper, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(BugDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BugDetailsLayout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addGroup(BugDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(TypeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(StatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(SeverityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(38, 38, 38)
                                        .addGroup(BugDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(SeverityBox, 0, 1, Short.MAX_VALUE)
                                            .addComponent(StatusBox, 0, 0, Short.MAX_VALUE)
                                            .addComponent(TypeBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 1, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BugDetailsLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(EditButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(93, 93, 93))))
                            .addComponent(Description, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE))
                        .addGap(42, 42, 42))))
        );
        BugDetailsLayout.setVerticalGroup(
            BugDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BugDetailsLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(BugDetailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(BugDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ProjectIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(StatusBox)
                    .addGroup(BugDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(IDOfProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(StatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(30, 30, 30)
                .addGroup(BugDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameOfBug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(BugDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TesterIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDOfTester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeverityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SeverityBox, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(BugDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeveloperNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdOfDeveloper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(BugDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DescriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Description, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65)
                .addGroup(BugDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Bug Details", BugDetails);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 1030, 760));

        setSize(new java.awt.Dimension(1384, 815));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 int choose=1;
    private void ProjectLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProjectLogoMouseClicked
    jTabbedPane1.setSelectedIndex(1);
    Dashlogo.setBackground(Black);
    Dashlogo.setForeground(Green);
    BugLogo.setBackground(Black);
    BugLogo.setForeground(Green);
    ProjectLogo.setBackground(Purple);
    ProjectLogo.setForeground(Black);
    choose=2;
    try
        {
             
           command=conObj.prepareStatement("select projects.projectid, projects.projectname, projects.creationdate , projects.creationtime FROM ASSIGNMENTS INNER JOIN PROJECTS ON PROJECTS.PROJECTID = ASSIGNMENTS.PROJECTID where ASSIGNMENTS.USERID=?" );
           //command=conObj.prepareStatement("SELECT userid, PROJECTID FROM ASSIGNMENTS AS AHMED WHERE USERID=?"+"SELECT projects.projectname, users.username from AHMED inner join users on users.userid= AHMED.userid INNER JOIN PROJECTS ON PROJECTS.PROJECTID = AHMED.PROJECTID");
          command.setInt(1,CurrentUser.id);
           resObj=command.executeQuery();
            Projects_table.setModel(DbUtils.resultSetToTableModel(resObj));
        }
        catch (SQLException ex)
        {
            System.out.println(ex.getMessage());
        }
           proj_number_all.setText(String.valueOf(Card(0)));

// TODO add your handling code here:
    }//GEN-LAST:event_ProjectLogoMouseClicked

    private void DashlogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashlogoMouseClicked
    jTabbedPane1.setSelectedIndex(0);
    Dashlogo.setBackground(Purple);
    Dashlogo.setForeground(Black);
    BugLogo.setBackground(Black);
    BugLogo.setForeground(Green);
    ProjectLogo.setBackground(Black);
    ProjectLogo.setForeground(Green);
    choose=1;
// TODO add your handling code here:
    }//GEN-LAST:event_DashlogoMouseClicked

    private void BugLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BugLogoMouseClicked
       jTabbedPane1.setSelectedIndex(2);
    Dashlogo.setBackground(Black);
    Dashlogo.setForeground(Green);
    BugLogo.setBackground(Purple);
    BugLogo.setForeground(Black);
    ProjectLogo.setBackground(Black);
    ProjectLogo.setForeground(Green);
    choose=3;
        try
        {
           command=conObj.prepareStatement("select bugs.bugname, bugs.description, bugs.dateassigned , bugs.dateresolved FROM BUGS WHERE DEVELOPERID = ?" );
           command.setInt(1,CurrentUser.id);
           resObj=command.executeQuery();
            Bugs_table.setModel(DbUtils.resultSetToTableModel(resObj));
        }
        catch (SQLException ex)
        {
            System.out.println(ex.getMessage());
        }
    BUG_number_all.setText(String.valueOf(Card(1)));

// TODO add your handling code here:
    }//GEN-LAST:event_BugLogoMouseClicked

    private void ProjectLogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProjectLogoMouseEntered
       if(choose==2){}
       else{
           ProjectLogo.setBackground(Gray);
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_ProjectLogoMouseEntered

    private void ProjectLogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProjectLogoMouseExited
        if (choose==2){}
        else{
       ProjectLogo.setBackground(Black);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_ProjectLogoMouseExited

    private void DashlogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashlogoMouseEntered
       if(choose==1){}
       else{
           Dashlogo.setBackground(Gray);
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_DashlogoMouseEntered

    private void DashlogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashlogoMouseExited
    if (choose==1){}
    else{
        Dashlogo.setBackground(Black);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_DashlogoMouseExited

    private void BugLogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BugLogoMouseEntered
       if(choose==3){}
       else{
          BugLogo.setBackground(Gray);
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_BugLogoMouseEntered

    private void BugLogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BugLogoMouseExited
       if (choose==3){}
    else{
        BugLogo.setBackground(Black);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BugLogoMouseExited

    private void LogoutLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutLogoMouseClicked
        Login y = new Login();
        y.show();
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_LogoutLogoMouseClicked

    private void LogoutLogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutLogoMouseEntered
        LogoutLogo.setBackground(Gray);
// TODO add your handling code here:
    }//GEN-LAST:event_LogoutLogoMouseEntered

    private void LogoutLogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutLogoMouseExited
        LogoutLogo.setBackground(Black);
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutLogoMouseExited

    private void noOfBugsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noOfBugsMouseClicked

    }//GEN-LAST:event_noOfBugsMouseClicked

    private void BUG_number_allMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BUG_number_allMouseClicked
        noOfBugsMouseClicked(evt);
    }//GEN-LAST:event_BUG_number_allMouseClicked

    private void Search3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Search3KeyReleased
        DefaultTableModel model = (DefaultTableModel) Bugs_table.getModel();

        String Searching = Search3.getText();

        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        Bugs_table.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(Searching));
    }//GEN-LAST:event_Search3KeyReleased

    private void Bugs_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bugs_tableMouseClicked
        try {
            jTabbedPane1.setSelectedIndex(3);
            System.out.println("storing the value of row choosen...");

            int selectedID = (int) Bugs_table.getValueAt(Bugs_table.getSelectedRow(), 0);
            CurrentBug bug = new CurrentBug((selectedID));
            BugId = CurrentBug.BugId;
            String[] arr = selectedBug(selectedID);

            jTabbedPane1.setSelectedIndex(3);
            NameOfBug.setEnabled(false);
            IDOfProject.setEnabled(false);
            IDOfTester.setEnabled(false);
            IdOfDeveloper.setEnabled(false);
            Description.setEnabled(false);
            StatusBox.setEnabled(false);
            SeverityBox.setEnabled(false);
            TypeBox.setEnabled(false);

            System.out.println("check if the status of this bug is closed or not to  make add&update&delete buttons to be unvisible...");
            String status = arr[6];
            System.out.println("status = " + arr[6]);

            if (status == null) {
                status = "---";
            }

            if (status.equals("C")) {
                ConfirmButton.setEnabled(false);
                EditButton.setVisible(false);
            } else if (!"C".equals(status) && Integer.parseInt(arr[3]) != CurrentUser.id) {
                ConfirmButton.setEnabled(false);
                EditButton.setVisible(false);
            } else if (!"C".equals(status) && Integer.parseInt(arr[3]) == CurrentUser.id) {
                ConfirmButton.setEnabled(false);
                EditButton.setVisible(true);
            }

            System.out.println("storing data in its place in text fields...");

            System.out.println("Name = " + arr[0]);
            NameOfBug.setText(arr[0]);

            System.out.println("PID = " + arr[1]);
            IDOfProject.setText(arr[1]);

            System.out.println("TNAME = " + arr[2]);
            IDOfTester.setText(arr[2]);

            System.out.println("DNAME = " + arr[4]);
            IdOfDeveloper.setText(arr[4]);

            System.out.println("Description = " + arr[5]);
            Description.setText(arr[5]);

            switch (status) {
                case "O":
                StatusBox.setSelectedIndex(1);
                break;
                case "I":
                StatusBox.setSelectedIndex(2);
                break;
                case "T":
                StatusBox.setSelectedIndex(3);
                break;
                case "C":
                StatusBox.setSelectedIndex(4);
                break;
                default:
                StatusBox.setSelectedIndex(0);
                break;
            }

            String Severity = arr[7];
            System.out.println("severity = " + Severity);

            if (Severity == null) {
                Severity = "---";
            }

            switch (Severity) {
                case "Critical":
                SeverityBox.setSelectedIndex(1);
                break;
                case "Major":
                SeverityBox.setSelectedIndex(2);
                break;
                case "Moderate":
                SeverityBox.setSelectedIndex(3);
                break;
                case "Minor":
                SeverityBox.setSelectedIndex(4);
                break;
                case "Cosmitic":
                SeverityBox.setSelectedIndex(5);
                break;
                default:
                SeverityBox.setSelectedIndex(0);
                break;
            }

            String Type = arr[8];
            System.out.println("Type = " + Type);

            if (Type == null) {
                Type = "---";
            }

            switch (Type) {
                case "Content":
                TypeBox.setSelectedIndex(1);
                break;
                case "Functional":
                TypeBox.setSelectedIndex(2);
                break;
                case "Visual":
                TypeBox.setSelectedIndex(3);
                break;
                default:
                TypeBox.setSelectedIndex(0);
                break;
            }

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }

    }//GEN-LAST:event_Bugs_tableMouseClicked

    private void Search2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Search2KeyReleased
        DefaultTableModel model = (DefaultTableModel) Projects_table.getModel();

        String Searching = Search2.getText();

        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        Projects_table.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(Searching));
    }//GEN-LAST:event_Search2KeyReleased

    private void Search2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search2ActionPerformed

    private void noOfBugs1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noOfBugs1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_noOfBugs1MouseClicked

    private void BUG_numberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BUG_numberMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BUG_numberMouseClicked

    private void CancelButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelButton1MouseClicked
        this.dispose();
    }//GEN-LAST:event_CancelButton1MouseClicked

    private void CancelButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelButton1MouseEntered
        CancelButton1.setBackground(Green);
    }//GEN-LAST:event_CancelButton1MouseEntered

    private void CancelButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelButton1MouseExited
        CancelButton1.setBackground(Purple);
    }//GEN-LAST:event_CancelButton1MouseExited

    private void CancelButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelButton1ActionPerformed

    private void ConfirmButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmButtonMouseClicked
        int TID;
        String status;
        String Severity = "";
        String Type = "";
        int done;
        
        if (edit == 1) {
            done =UpdateStatus((int) StatusBox.getSelectedItem());
            if (done == 1) {
                JOptionPane.showMessageDialog(this, "Information Updated succesfully");
                jTabbedPane1.setSelectedIndex(0);

                // RELOAD TABLE
                ViewProjectBugsTable();
                 Bugs_table.setModel(DbUtils.resultSetToTableModel(getResObj()));

                jTabbedPane1.setSelectedIndex(2);
            }

        }
    }//GEN-LAST:event_ConfirmButtonMouseClicked
  public ResultSet getResObj() {
        return resObj;
    }
    public int UpdateStatus(int Status) {
        try {
           // String status = " ";
            conObj = DriverManager.getConnection(host, uname, pass);
            smtObj = conObj.createStatement( ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY );
            command=conObj.prepareStatement("SELECT * FROM BUGS" );

            command = conObj.prepareStatement("UPDATE BUGS SET STATUS = ?");
            command.setInt(1,Status);


            System.out.println(" excute the query...");

            command.executeUpdate();
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        return 1;
    }
  public void ViewProjectBugsTable() {
        try {
            conObj = DriverManager.getConnection(host, uname, pass);
            smtObj = conObj.createStatement( ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY );
            command=conObj.prepareStatement("SELECT * FROM BUGS" );

            System.out.println(" prepare the query...");

            command = conObj.prepareStatement("SELECT * FROM BUGS WHERE PROJECTID = ? ORDER BY BUGID ASC");
            command.setInt(1, CurrentProject.projectId);

            System.out.println(" excute the query...");

            resObj = command.executeQuery();
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }
    private void ConfirmButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmButtonMouseEntered
        ConfirmButton.setBackground(Green);
    }//GEN-LAST:event_ConfirmButtonMouseEntered

    private void ConfirmButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmButtonMouseExited
        ConfirmButton.setBackground(Purple);
    }//GEN-LAST:event_ConfirmButtonMouseExited

    private void ConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmButtonActionPerformed

    private void EditButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditButtonMouseClicked
        edit = 1;
        Description.setEnabled(false);
        StatusBox.setEnabled(true);
        SeverityBox.setEnabled(false);
        TypeBox.setEnabled(false);
        ConfirmButton.setEnabled(false);
        BugId = CurrentBug.BugId;
    }//GEN-LAST:event_EditButtonMouseClicked

    private void EditButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditButtonMouseEntered
        EditButton.setBackground(Purple);
    }//GEN-LAST:event_EditButtonMouseEntered

    private void EditButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditButtonMouseExited
        EditButton.setBackground(Green);
    }//GEN-LAST:event_EditButtonMouseExited

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditButtonActionPerformed

    private void NameOfBugFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameOfBugFocusLost
       // if (BugDetail.ChechDuplicity(NameOfBug.getText())) {
         //   JOptionPane.showMessageDialog(this, " Sorry this name is exist , please choose another name");
           // NameOfBug.setText("");
       // }
    }//GEN-LAST:event_NameOfBugFocusLost

    private void IdOfDeveloperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdOfDeveloperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdOfDeveloperActionPerformed

    private void DescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescriptionActionPerformed
    int BugId = 0;  //FOR STORING THE BUGID  
    int edit = 0; // USED AS AN INDICATOR FOR UPDATE OPERATION
    int add = 0; //USED AS AN INDICATOR FOR INSERT OPERATION
    
    public String[] selectedBug(int id) {
        String retName = " ";
        String retPID = " ";
        String retTID = " ";
        String retDID = " ";
        String retDescription = " ";
        String retStatus = " ";
        String retSeverity = " ";
        String retType = " ";
        String retTNAME = "";
        String retDNAME = "";

        try {
            
            conObj = DriverManager.getConnection(host, uname, pass);
            smtObj = conObj.createStatement( ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY );
            resObj = smtObj.executeQuery("SELECT * FROM BUGS");
            
            System.out.println(" prepare the query...");

            command = conObj.prepareStatement("SELECT * FROM BUGS WHERE BUGID = ?");
            command.setInt(1, id);

            System.out.println(" excute the query...");

            resObj = command.executeQuery();
            resObj.next();

            retName = resObj.getString("BUGNAME");
            System.out.println(retName);

            retPID = Integer.toString(resObj.getInt("PROJECTID"));
            System.out.println(retPID);

            retTID = Integer.toString(resObj.getInt("TESTERID"));
            System.out.println(retTID);

            retDID = Integer.toString(resObj.getInt("DEVELOPERID"));
            System.out.println(retDID);

            retDescription = resObj.getString("DESCRIPTION");
            System.out.println(retDescription);

            retStatus = resObj.getString("STATUS");
            System.out.println(retStatus);

            retSeverity = resObj.getString("SEVERITY");
            System.out.println(retSeverity);

            retType = resObj.getString("TYBE");
            System.out.println(retType);

            //RETURN TESTERNAME
            System.out.println(" prepare the query...");

            command = conObj.prepareStatement("SELECT * FROM USERS WHERE USERID = ?");
            command.setInt(1, Integer.parseInt(retTID));

            System.out.println(" excute the query...");

            resObj = command.executeQuery();
            resObj.next();
            retTNAME = resObj.getString("USERNAME");

            //RETURN DEVELOPERNAME
            System.out.println(" prepare the query...");

            command = conObj.prepareStatement("SELECT * FROM USERS WHERE USERID = ?");
            command.setInt(1, Integer.parseInt(retDID));

            System.out.println(" excute the query...");

            resObj = command.executeQuery();
            resObj.next();
            retDNAME = resObj.getString("USERNAME");

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        return new String[]{retName, retPID, retTNAME, retTID, retDNAME, retDescription, retStatus, retSeverity, retType};
    }
    
    
    
    int counter=0;
    public int Card(int A) {
        counter=0;
        try {
            if(A==0){
            command = conObj.prepareStatement("SELECT * FROM ASSIGNMENTS WHERE USERID =?");
            command.setInt(1, CurrentUser.id);
            resObj = command.executeQuery();
            }
            else if (A==1){
            command = conObj.prepareStatement("SELECT * FROM BUGS WHERE DEVELOPERID =?");
            command.setInt(1, CurrentUser.id);
            }
            resObj = command.executeQuery();
            while (resObj.next()) {
                counter++;
            }
        } catch (SQLException ex) {
           
        }
        return counter;
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
            
            }
        catch (Exception ex) {
            java.util.logging.Logger.getLogger(Devoloper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Devoloper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BUG_number;
    private javax.swing.JLabel BUG_number_all;
    private javax.swing.JPanel BugDetails;
    private javax.swing.JLabel BugDetailsLabel;
    private javax.swing.JLabel BugLogo;
    private javax.swing.JLabel BugNumber;
    private javax.swing.JLabel BugNumber1;
    private javax.swing.JTable Bugs_table;
    private javax.swing.JButton CancelButton1;
    private javax.swing.JButton ConfirmButton;
    private javax.swing.JTable Dashboard_table;
    private javax.swing.JLabel Dashlogo;
    private javax.swing.JTextField Description;
    private javax.swing.JLabel DescriptionLabel;
    private javax.swing.JLabel DeveloperName;
    private javax.swing.JLabel DeveloperNameLabel;
    private javax.swing.JButton EditButton;
    private javax.swing.JTextField IDOfProject;
    private javax.swing.JTextField IDOfTester;
    private javax.swing.JTextField IdOfDeveloper;
    private javax.swing.JLabel LogoOfSearch;
    private javax.swing.JLabel LogoOfSearch1;
    private javax.swing.JLabel LogoutLogo;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameOfBug;
    private javax.swing.JLabel ProjectIdLabel;
    private javax.swing.JLabel ProjectLogo;
    private javax.swing.JLabel ProjectNumber;
    private javax.swing.JLabel ProjectNumber2;
    private javax.swing.JTable Projects_table;
    private app.bolivia.swing.JCTextField Search2;
    private app.bolivia.swing.JCTextField Search3;
    private javax.swing.JComboBox<String> SeverityBox;
    private javax.swing.JLabel SeverityLabel;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JComboBox<String> StatusBox;
    private javax.swing.JLabel StatusLabel;
    private javax.swing.JLabel TesterIdLabel;
    private javax.swing.JComboBox<String> TypeBox;
    private javax.swing.JLabel TypeLabel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel noOfBugs;
    private javax.swing.JPanel noOfBugs1;
    private javax.swing.JPanel noOfProjects;
    private javax.swing.JPanel noOfProjects1;
    private javax.swing.JLabel proj_number;
    private javax.swing.JLabel proj_number_all;
    private javax.swing.JLabel testerLogo;
    // End of variables declaration//GEN-END:variables
}
