/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bugtrackingsystem;

/**
 *
 * @author mariam
 */
public class Intro extends javax.swing.JFrame {

    /**
     * Creates new form Intro
     */
    public Intro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        introProgressBar = new javax.swing.JProgressBar();
        percentage = new javax.swing.JLabel();
        AhmedKhaled = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        SystemName = new javax.swing.JLabel();
        MahmoudEhab = new javax.swing.JLabel();
        MariamMohamed = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bug Tracking System");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(50, 50, 50));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(550, 400));

        introProgressBar.setBackground(new java.awt.Color(217, 217, 217));
        introProgressBar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        introProgressBar.setForeground(new java.awt.Color(109, 177, 147));
        introProgressBar.setPreferredSize(new java.awt.Dimension(402, 14));

        percentage.setBackground(new java.awt.Color(109, 177, 147));
        percentage.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        percentage.setForeground(new java.awt.Color(109, 177, 147));
        percentage.setText("%");

        AhmedKhaled.setBackground(new java.awt.Color(207, 222, 231));
        AhmedKhaled.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        AhmedKhaled.setForeground(new java.awt.Color(133, 89, 165));
        AhmedKhaled.setText("Ahmed Khaled");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bugtrackingsystem/icons/images/logo.png"))); // NOI18N
        logo.setPreferredSize(new java.awt.Dimension(190, 190));

        SystemName.setBackground(new java.awt.Color(207, 222, 231));
        SystemName.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        SystemName.setForeground(new java.awt.Color(133, 89, 165));
        SystemName.setText("Bug Tracking System");

        MahmoudEhab.setBackground(new java.awt.Color(207, 222, 231));
        MahmoudEhab.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        MahmoudEhab.setForeground(new java.awt.Color(133, 89, 165));
        MahmoudEhab.setText("Mahmoud Ehab");

        MariamMohamed.setBackground(new java.awt.Color(207, 222, 231));
        MariamMohamed.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        MariamMohamed.setForeground(new java.awt.Color(133, 89, 165));
        MariamMohamed.setText("Mariam Mohamed");

        p1.setBackground(new java.awt.Color(207, 222, 231));
        p1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        p1.setForeground(new java.awt.Color(133, 89, 165));
        p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bugtrackingsystem/icons/images/person intro.png"))); // NOI18N

        p2.setBackground(new java.awt.Color(207, 222, 231));
        p2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        p2.setForeground(new java.awt.Color(133, 89, 165));
        p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bugtrackingsystem/icons/images/person intro.png"))); // NOI18N

        p3.setBackground(new java.awt.Color(207, 222, 231));
        p3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        p3.setForeground(new java.awt.Color(133, 89, 165));
        p3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bugtrackingsystem/icons/images/person intro.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SystemName)
                .addGap(151, 151, 151))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(introProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AhmedKhaled, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MahmoudEhab)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MariamMohamed, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(percentage)
                .addGap(264, 264, 264))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SystemName)
                .addGap(18, 18, 18)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AhmedKhaled, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MariamMohamed, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MahmoudEhab, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(percentage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(introProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Intro Page = new Intro();
       Page.setVisible(true);
       try{
           for (int i = 0; i<=100; i++){
               Thread.sleep(90);
               Page.introProgressBar.setValue(i);
               Page.percentage.setText(Integer.toString(i)+ "%");
           };
       }
       catch(Exception e){
           System.out.print(e);
       }
       new Login().setVisible(true);
       Page.dispose();
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AhmedKhaled;
    private javax.swing.JLabel MahmoudEhab;
    private javax.swing.JLabel MariamMohamed;
    private javax.swing.JLabel SystemName;
    private javax.swing.JProgressBar introProgressBar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel percentage;
    // End of variables declaration//GEN-END:variables
}
